from __future__ import annotations

from django.db.models.signals import post_delete
from django.dispatch import receiver

from .models import AnalysisArtifact, Dataset
from .storage import delete_field_file


@receiver(post_delete, sender=Dataset)
def delete_dataset_blob(sender, instance: Dataset, **kwargs) -> None:
    """Delete private content after a dataset row or guest cascade is removed."""

    delete_field_file(instance.file)


@receiver(post_delete, sender=AnalysisArtifact)
def delete_artifact_blob(sender, instance: AnalysisArtifact, **kwargs) -> None:
    """Delete generated bytes when their job or project is removed."""

    delete_field_file(instance.file)
