# Generated by Django 5.1.7 on 2026-08-12 06:59

import analyses.storage
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('visibility', models.CharField(choices=[('private', 'Private')], default='private', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(storage=analyses.storage.dataset_storage, upload_to=analyses.storage.dataset_upload_to)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(default='text/csv', max_length=100)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('row_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('column_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('columns', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='analyses.analysisproject')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(choices=[('event_count_donor_ignorant', 'Event count, donor ignorant'), ('event_count_donor_aware', 'Event count, donor aware'), ('trajectory_donor_ignorant', 'Trajectory, donor ignorant')], max_length=40)),
                ('configuration', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=16)),
                ('progress', models.FloatField(default=0.0)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True, max_length=2000)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='analyses.analysisproject')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='analyses.dataset')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GuestSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('token_hint', models.CharField(editable=False, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_guest_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='analysisproject',
            name='owner_guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='analyses.guestsession'),
        ),
        migrations.CreateModel(
            name='ProjectShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('token_hint', models.CharField(editable=False, max_length=16)),
                ('allow_dataset_download', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_share_links', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='analyses.analysisproject')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['project', 'created_at'], name='analyses_da_project_bfd6c7_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['project', 'created_at'], name='analyses_an_project_8b792d_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['status', 'created_at'], name='analyses_an_status_102c15_idx'),
        ),
        migrations.AddConstraint(
            model_name='analysisjob',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('project', 'idempotency_key'), name='unique_job_idempotency_key_per_project'),
        ),
        migrations.AddConstraint(
            model_name='analysisjob',
            constraint=models.CheckConstraint(condition=models.Q(('progress__gte', 0.0), ('progress__lte', 1.0)), name='job_progress_between_zero_and_one'),
        ),
        migrations.AddIndex(
            model_name='guestsession',
            index=models.Index(fields=['expires_at', 'revoked_at'], name='analyses_gu_expires_bb7fb2_idx'),
        ),
        migrations.AddConstraint(
            model_name='analysisproject',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner_user__isnull', False), ('owner_guest__isnull', True)), models.Q(('owner_user__isnull', True), ('owner_guest__isnull', False)), _connector='OR'), name='project_has_exactly_one_owner'),
        ),
        migrations.AddIndex(
            model_name='projectsharelink',
            index=models.Index(fields=['expires_at', 'revoked_at'], name='analyses_pr_expires_d136e2_idx'),
        ),
    ]
