# Generated by Django 5.1.7 on 2026-08-12 07:17

import analyses.models
import analyses.storage
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.SlugField(max_length=64)),
                ('file', models.FileField(storage=analyses.storage.AliasStorage('artifacts'), upload_to=analyses.models.artifact_upload_to)),
                ('filename', models.CharField(max_length=180)),
                ('content_type', models.CharField(default='application/octet-stream', max_length=100)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('shareable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='analyses.analysisjob')),
            ],
            options={
                'ordering': ('created_at',),
                'constraints': [models.UniqueConstraint(fields=('job', 'role'), name='unique_artifact_role_per_job')],
            },
        ),
    ]
