# Generated by Django 5.1.7 on 2026-08-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0002_analysisartifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='progress_detail',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
