# Generated by Django 5.1.7 on 2026-08-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("analyses", "0003_job_progress_detail")]

    operations = [
        migrations.AlterField(
            model_name="analysisartifact",
            name="shareable",
            field=models.BooleanField(default=False),
        )
    ]
