[theme]
base = "light"
primaryColor = "#0F6B78"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F7F7"
textColor = "#262A33"
font = "monospace"

[server]
headless = true
maxUploadSize = 1
enableXsrfProtection = true

[browser]
gatherUsageStats = false
